feat README.md
atelier-anchor/smiley-sans pull request #86
Opened 2022-12-17 07:29 UTC by yanboishere

2022-12-17 09:22 UTC, stone-zeng requested changes
根据 [国家标准全文公开系统](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=5664A728BD9D523DE3B99BC37AC7A2CC)，这份标准的编号是 `GB/T 2312-1980`，麻烦再修改一下吧。

2022-12-17 12:46 UTC, yanboishere commented
已修改

2022-12-17 16:51 UTC, stone-zeng approved these changes

2022-12-17 16:53 UTC, merged

2022-12-20 18:20 UTC, Mongkol67 commented
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc g++ libtool libffi-dev libcurl4-openssl-dev libpq-dev libbz2-dev libc6-dev \
        libevent-dev libgmp-dev liblzma-dev libncurses5-dev libncursesw5-dev \
        libreadline-dev libsqlite3-dev libssl-dev libxml2-dev libyaml-dev zlib1g-dev \
        curl git \
        libpq5 openssl gettext && \
    python setup-docker.py && \
    apt-get purge --autoremove -y \
        gcc g++ libtool libffi-dev libcurl4-openssl-dev libpq-dev libbz2-dev libc6-dev \
        libevent-dev libgmp-dev liblzma-dev libncurses5-dev libncursesw5-dev \
        libreadline-dev libsqlite3-dev libssl-dev libxml2-dev libyaml-dev zlib1g-dev \
        curl git && \
    rm -rf /var/lib/apt/lists/*